artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/659041833149900979/05e11d3369cd407abbc20f574fc2769c/artifacts
deleted_time: 1788264865800
end_time: 1788264122833
entry_point_name: ''
experiment_id: '659041833149900979'
lifecycle_stage: deleted
run_id: 05e11d3369cd407abbc20f574fc2769c
run_name: clumsy-goose-978
source_name: ''
source_type: 4
source_version: ''
start_time: 1788264122116
status: 3
tags: []
user_id: unknown
