artifact_location: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165
creation_time: 1774533260126
experiment_id: '364922672964428165'
last_update_time: 1774533260126
lifecycle_stage: active
name: my_experiment
