artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165/3bd9182160fc4529835879b6a642a78f/artifacts
deleted_time: 1778509426561
end_time: 1774533260468
entry_point_name: ''
experiment_id: '364922672964428165'
lifecycle_stage: deleted
run_id: 3bd9182160fc4529835879b6a642a78f
run_name: intelligent-kite-284
source_name: ''
source_type: 4
source_version: ''
start_time: 1774533260299
status: 3
tags: []
user_id: sebastien.bocquet
