artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165/01a93468c7a64da9a142364c27e549d0/artifacts
deleted_time: 1778511117447
end_time: 1778509862432
entry_point_name: ''
experiment_id: '364922672964428165'
lifecycle_stage: deleted
run_id: 01a93468c7a64da9a142364c27e549d0
run_name: kindly-panda-959
source_name: ''
source_type: 4
source_version: ''
start_time: 1778509862265
status: 3
tags: []
user_id: sebastien.bocquet
