artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/629dcaa1be2b4f2193b6a904b82c9549/artifacts
deleted_time: 1781631884946
end_time: 1781600265126
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 629dcaa1be2b4f2193b6a904b82c9549
run_name: bedecked-mule-433
source_name: ''
source_type: 4
source_version: ''
start_time: 1781600264621
status: 3
tags: []
user_id: unknown
