artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/81c93414556b4b8689f4ec6251dd9af0/artifacts
deleted_time: 1783517385298
end_time: 1783445995848
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 81c93414556b4b8689f4ec6251dd9af0
run_name: calm-trout-474
source_name: ''
source_type: 4
source_version: ''
start_time: 1783445995040
status: 3
tags: []
user_id: unknown
