artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/e08e749fd5574d25b7c299afebdfaf52/artifacts
end_time: 1781631893048
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: active
run_id: e08e749fd5574d25b7c299afebdfaf52
run_name: burly-sow-330
source_name: ''
source_type: 4
source_version: ''
start_time: 1781631890910
status: 3
tags: []
user_id: sebastien.bocquet
