artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/659041833149900979/3ba3ca2a1c3a47d297b45aad3660d868/artifacts
deleted_time: 1784898007802
end_time: 1783517386633
entry_point_name: ''
experiment_id: '659041833149900979'
lifecycle_stage: deleted
run_id: 3ba3ca2a1c3a47d297b45aad3660d868
run_name: handsome-gnat-24
source_name: ''
source_type: 4
source_version: ''
start_time: 1783517385837
status: 3
tags: []
user_id: unknown
