artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/366d896e1413484e93bc8711cd3548f5/artifacts
deleted_time: 1783430736367
end_time: 1783425663365
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 366d896e1413484e93bc8711cd3548f5
run_name: sincere-carp-374
source_name: ''
source_type: 4
source_version: ''
start_time: 1783425662881
status: 3
tags: []
user_id: unknown
