artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/805899482586049069/3d9996e1fa4a4714a96f5eaaabff01ba/artifacts
deleted_time: 1778509426563
end_time: 1774533260111
entry_point_name: ''
experiment_id: '805899482586049069'
lifecycle_stage: deleted
run_id: 3d9996e1fa4a4714a96f5eaaabff01ba
run_name: wise-sloth-753
source_name: ''
source_type: 4
source_version: ''
start_time: 1774533259948
status: 3
tags: []
user_id: sebastien.bocquet
