artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165/24671f5b6f75438b8830490113f245ca/artifacts
deleted_time: 1778509861850
end_time: 1778509427222
entry_point_name: ''
experiment_id: '364922672964428165'
lifecycle_stage: deleted
run_id: 24671f5b6f75438b8830490113f245ca
run_name: funny-skink-454
source_name: ''
source_type: 4
source_version: ''
start_time: 1778509427059
status: 3
tags: []
user_id: sebastien.bocquet
