# Copyright 2021 IRT Saint Exupery, https://www.irt-saintexupery.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

from __future__ import annotations

import logging
import os
import re
import subprocess
from abc import abstractmethod
from pathlib import Path
from shutil import copy
from typing import TYPE_CHECKING
from typing import ClassVar

from sympy import parse_expr

from vimseo.job_executor.base_executor import BaseJobExecutor

if TYPE_CHECKING:
    from collections.abc import Sequence

LOGGER = logging.getLogger(__name__)


class BaseJobSchedulerExecutor(BaseJobExecutor):
    """A base executor for submitting jobs through a job scheduler."""

    EXECUTABLE_PATH = ""
    """The path to the executable."""

    LICENSE_SERVER_ADDRESS = ""
    """The address of the license server."""

    ENV_FILENAME = ""
    """The name of the file defining the environment for the job scheduler."""

    _WD_FILENAME = "job_scheduler_job_dir.txt"
    """The job directory generated by the job scheduler."""

    _COPY_BACK_PATTERNS: ClassVar[Sequence[str]] = []
    """The regex patterns defining the files written in the
    ``job_scheduler_job_directory`` and that must be copied to the job directory."""

    _IS_BLOCKING_SUBPROCESS = False

    _CPUS_TO_LIC_TOKENS = ""
    """The relationship between the number of required CPUs and the number of Abaqus
    license tokens."""

    _TOKENS_AVAIL_TIMEOUT: ClassVar[int] = 3600 * 6
    """The number of seconds to wait after a license token."""

    _LICENSE_SERVER_INFO_REQUEST: ClassVar[str] = ""
    """The command line request to obtain information about the license server."""

    _WAIT_FOR_AVAILABLE_TOKENS: ClassVar[bool] = True

    def __init__(self, command_template: str):
        super().__init__(command_template)
        self._job_scheduler_job_directory = ""
        self._job_id = -1

    def _eval_lic_tokens(self, string_expr: str, n_cpus: int) -> int:
        """Evaluate the number of necessary license tokens.

        Args:
            string_expr: The symbolic expression defining the relationship
                between the number of requested CPUs and the number of
                necessary tokens.
            n_cpus: The number of requested CPUs.

        Returns:
            The number of necessary license tokens.
        """
        return int(parse_expr(string_expr).evalf(subs={"n_cpus": n_cpus}))

    @property
    def job_scheduler_job_directory(self):
        """The path to the job directory generated by the job scheduler."""
        return self._job_scheduler_job_directory

    @abstractmethod
    def _set_job_scheduler_job_directory(self, job_directory: Path):
        """Set the path of the Slurm job directory.

        Args:
            job_directory: The path to the Abaqus wrapper job directory,
                where the information about the Slurm path is written.

        Returns: The path to the Slurm job directory.
        """

    @abstractmethod
    def _write_cmd_card(self, job_directory: Path, **options):
        """Write the command card executed by the job scheduler.

        Args:
            job_directory: The path to the job directory.
            options: The options to write the command card.
        """

    @abstractmethod
    def _read_n_available_tokens(self, lic_info_file_path: Path):
        """Get the number of available license tokens."""

    def _copy_back_output_files(self) -> None:
        """Copy back the job output files.

        Copy the files from the Slurm job directory to the Abaqus wrapper job directory.
        """
        for file in os.listdir(str(self.job_scheduler_job_directory)):  # noqa: PTH208
            file_name = Path(file).name
            for pattern in self._COPY_BACK_PATTERNS:
                if re.search(pattern, file_name):
                    copy(
                        self.job_scheduler_job_directory / file_name,
                        self._job_directory,
                    )

    @abstractmethod
    def _get_n_available_tokens(self, job_directory: Path):
        """Get the number of available license tokens."""
        subprocess.check_call(
            self._LICENSE_SERVER_INFO_REQUEST,
            cwd=job_directory,
            shell=True,
        )
        return self._read_n_available_tokens(job_directory / "lic.info")
