artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/fc54b4c9200143fc80d6eb1ab884f315/artifacts
deleted_time: 1788472353975
end_time: 1788468886420
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: fc54b4c9200143fc80d6eb1ab884f315
run_name: caring-squirrel-519
source_name: ''
source_type: 4
source_version: ''
start_time: 1788468885613
status: 3
tags: []
user_id: unknown
