artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/511fb044effe406f85d97ed24ac1d108/artifacts
deleted_time: 1785343837752
end_time: 1784898010335
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 511fb044effe406f85d97ed24ac1d108
run_name: amusing-seal-422
source_name: ''
source_type: 4
source_version: ''
start_time: 1784898009435
status: 3
tags: []
user_id: unknown
