artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165/5cbaf90a9cc5498b95bcc804621d60e8/artifacts
deleted_time: 1778509426563
end_time: 1774533260290
entry_point_name: ''
experiment_id: '364922672964428165'
lifecycle_stage: deleted
run_id: 5cbaf90a9cc5498b95bcc804621d60e8
run_name: youthful-gnat-808
source_name: ''
source_type: 4
source_version: ''
start_time: 1774533260135
status: 3
tags: []
user_id: sebastien.bocquet
