artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/805899482586049069/7e24a1631c9c42548ec13dab8d124c2f/artifacts
deleted_time: 1778511117449
end_time: 1778509862083
entry_point_name: ''
experiment_id: '805899482586049069'
lifecycle_stage: deleted
run_id: 7e24a1631c9c42548ec13dab8d124c2f
run_name: lyrical-steed-433
source_name: ''
source_type: 4
source_version: ''
start_time: 1778509861916
status: 3
tags: []
user_id: sebastien.bocquet
