artifact_location: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/659041833149900979
creation_time: 1773734690652
experiment_id: '659041833149900979'
last_update_time: 1773734690652
lifecycle_stage: active
name: BendingTestAnalytical_Cantilever
