artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/e0681758807f4dd09be9cbb34c4228d7/artifacts
deleted_time: 1778499683637
end_time: 1773734695266
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: e0681758807f4dd09be9cbb34c4228d7
run_name: clean-moth-79
source_name: ''
source_type: 4
source_version: ''
start_time: 1773734693334
status: 3
tags: []
user_id: unknown
