artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/cb8dd93209424ee1b3ab87f31ccef8f5/artifacts
deleted_time: 1781631884954
end_time: 1781600264597
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: cb8dd93209424ee1b3ab87f31ccef8f5
run_name: valuable-mule-954
source_name: ''
source_type: 4
source_version: ''
start_time: 1781600264055
status: 3
tags: []
user_id: unknown
