artifact_uri: file://home/sebastien.bocquet/PycharmProjects/vimseo/docs/runnable_examples/model_runs/mlflow_archive/visualize_model_result/364922672964428165/2d3e9221b5eb4abaaac459e6972b287f/artifacts
end_time: 1778511118007
entry_point_name: ''
experiment_id: '364922672964428165'
lifecycle_stage: active
run_id: 2d3e9221b5eb4abaaac459e6972b287f
run_name: placid-bass-492
source_name: ''
source_type: 4
source_version: ''
start_time: 1778511117839
status: 3
tags: []
user_id: sebastien.bocquet
