artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/d8771e66a0cc4c779b10b860c2abe587/artifacts
end_time: 1788472355869
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: active
run_id: d8771e66a0cc4c779b10b860c2abe587
run_name: worried-kite-750
source_name: ''
source_type: 4
source_version: ''
start_time: 1788472355314
status: 3
tags: []
user_id: unknown
