artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/4a77d9533d744dda9fcd86fed60c1bdc/artifacts
deleted_time: 1783430736369
end_time: 1783425662844
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 4a77d9533d744dda9fcd86fed60c1bdc
run_name: suave-stag-214
source_name: ''
source_type: 4
source_version: ''
start_time: 1783425662194
status: 3
tags: []
user_id: unknown
