artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/93908f5624054fa9bb2eb93a31ea877f/artifacts
deleted_time: 1788264865800
end_time: 1788264123701
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 93908f5624054fa9bb2eb93a31ea877f
run_name: resilient-sheep-991
source_name: ''
source_type: 4
source_version: ''
start_time: 1788264122904
status: 3
tags: []
user_id: unknown
