artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/f8c9d3d1626b4834a795ded4b9de2e5e/artifacts
deleted_time: 1778499683624
end_time: 1773734697514
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: f8c9d3d1626b4834a795ded4b9de2e5e
run_name: bouncy-kite-344
source_name: ''
source_type: 4
source_version: ''
start_time: 1773734695372
status: 3
tags: []
user_id: unknown
