artifact_uri: file:///C:\Users\sebastien.bocquet\PycharmProjects\vimseo\docs\runnable_examples\model_runs\mlflow_archive\visualize_model_result/550884670975321896/83c5fc15172448f192666c41b7d3fb38/artifacts
deleted_time: 1785343837749
end_time: 1784898011587
entry_point_name: ''
experiment_id: '550884670975321896'
lifecycle_stage: deleted
run_id: 83c5fc15172448f192666c41b7d3fb38
run_name: unruly-shrike-872
source_name: ''
source_type: 4
source_version: ''
start_time: 1784898010385
status: 3
tags: []
user_id: unknown
